Python 2.7.6 (default, Mar 22 2014, 22:59:38) 
[GCC 4.8.2] on linux2
Type "copyright", "credits" or "license()" for more information.
>>> ================================ RESTART ================================
>>> 

Traceback (most recent call last):
  File "/media/will/6436-E835/Documents/Serial Desktop App/basicSerialGui.py", line 2, in <module>
    import tkinter.scrolledtext as tkst
ImportError: No module named tkinter.scrolledtext
>>> ================================ RESTART ================================
>>> 
>>> ================================ RESTART ================================
>>> 
as
there was no space

>>> ================================ RESTART ================================
>>> 
a
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1489, in __call__
    return self.func(*args)
  File "/media/will/6436-E835/Documents/Serial Desktop App/basicSerialGui.py", line 27, in onPressEnter
    self.TextEntryBox.configure(state=ENABLE)
NameError: global name 'ENABLE' is not defined
aA
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1489, in __call__
    return self.func(*args)
  File "/media/will/6436-E835/Documents/Serial Desktop App/basicSerialGui.py", line 27, in onPressEnter
    self.TextEntryBox.configure(state=ENABLE)
NameError: global name 'ENABLE' is not defined

>>> ================================ RESTART ================================
>>> 

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1489, in __call__
    return self.func(*args)
  File "/media/will/6436-E835/Documents/Serial Desktop App/basicSerialGui.py", line 27, in onPressEnter
    self.TextEntryBox.configure(state='ENABLE')
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1274, in configure
    return self._configure('configure', cnf, kw)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1265, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
TclError: bad state "ENABLE": must be disabled, normal, or readonly
a
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1489, in __call__
    return self.func(*args)
  File "/media/will/6436-E835/Documents/Serial Desktop App/basicSerialGui.py", line 27, in onPressEnter
    self.TextEntryBox.configure(state='ENABLE')
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1274, in configure
    return self._configure('configure', cnf, kw)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1265, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
TclError: bad state "ENABLE": must be disabled, normal, or readonly

>>> ================================ RESTART ================================
>>> 
State
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1489, in __call__
    return self.func(*args)
  File "/media/will/6436-E835/Documents/Serial Desktop App/basicSerialGui.py", line 27, in onPressEnter
    self.TextEntryBox.configure(state='NORMAL')
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1274, in configure
    return self._configure('configure', cnf, kw)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1265, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
TclError: bad state "NORMAL": must be disabled, normal, or readonly

>>> ================================ RESTART ================================
>>> 

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1489, in __call__
    return self.func(*args)
  File "/media/will/6436-E835/Documents/Serial Desktop App/basicSerialGui.py", line 27, in onPressEnter
    self.TextEntryBox.configure(state=normal)
NameError: global name 'normal' is not defined

>>> ================================ RESTART ================================
>>> 



>>> ================================ RESTART ================================
>>> 

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1489, in __call__
    return self.func(*args)
  File "/media/will/6436-E835/Documents/Serial Desktop App/basicSerialGui.py", line 28, in onPressEnter
    self.MesageBox.configure(state='disabled')
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1848, in __getattr__
    return getattr(self.tk, attr)
AttributeError: MesageBox

>>> ================================ RESTART ================================
>>> 

A
Aslan

>>> ================================ RESTART ================================
>>> 

>>> ================================ RESTART ================================
>>> 
>>> 
